---
description: "Hakkında daha fazla bilgi edinin: ' TRY ' ifadesinin dışında ' catch ' bulunamaz"
title: "' TRY ' ifadesinin dışında ' catch ' bulunamaz"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 4ac18a51602c7dc5c4d7b397e1b64f9ed77fcc87
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473907"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>' TRY ' ifadesinin dışında ' catch ' bulunamaz

`Catch` bir `Try...Catch...Finally` ifade bloğunda yer almalıdır. `Catch`Blodaha gereksiz bir deyime sahipsiniz ya da `Try` `Catch` deyiminiz karşılık gelen bloğunun sınırları dışında görünüyor `Try` .  
  
 **Hata kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. Gerekli değilse, `Catch` ifadeyi silin veya bir `Try...Catch...Finally` ifade bloğuna yerleştirin.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../language-reference/statements/try-catch-finally-statement.md)
