---
title: "' TRY ' ifadesinin dışında ' catch ' bulunamaz"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: b5097910fa669c320e2e1b57d8d090b5d66f0956
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074530"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>' TRY ' ifadesinin dışında ' catch ' bulunamaz

`Catch` bir `Try...Catch...Finally` ifade bloğunda yer almalıdır. `Catch`Blodaha gereksiz bir deyime sahipsiniz ya da `Try` `Catch` deyiminiz karşılık gelen bloğunun sınırları dışında görünüyor `Try` .  
  
 **Hata kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. Gerekli değilse, `Catch` ifadeyi silin veya bir `Try...Catch...Finally` ifade bloğuna yerleştirin.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../language-reference/statements/try-catch-finally-statement.md)
