---
title: "' ', ' ' <name1> Öğesinden devraldığından ' catch ' bloğuna hiç ulaşılamadı. <name2>"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 560beddd1e9051c43d610fe893a55baa2a5c559a
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395655"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>' ', ' ' \<name1> Öğesinden devraldığından ' catch ' bloğuna hiç ulaşılamadı. \<name2>
`Catch`Kod içindeki bir bloğa hiç ulaşılamadı.  
  
 Bu ileti, varsayılan olarak bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak değerlendirme hakkında daha fazla bilgi için bkz. [Visual Basic uyarıları yapılandırma](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Hata kimliği:** BC42029  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
- Yabancı bloğu kaldırın `Catch` .  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Özel durumları yakalamak için try/catch bloğunu kullanma](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally Deyimi](../language-reference/statements/try-catch-finally-statement.md)
