---
description: 'Daha fazla bilgi edinin: özel durumlar'
title: Özel durumlar
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: 71cf6a4ac23f7979d0c9137d88f36a45f71783a3
ms.sourcegitcommit: ddf7edb67715a5b9a45e3dd44536dabc153c1de0
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/06/2021
ms.locfileid: "99742465"
---
# <a name="exceptions"></a><span data-ttu-id="02352-103">Özel durumlar</span><span class="sxs-lookup"><span data-stu-id="02352-103">Exceptions</span></span>

<span data-ttu-id="02352-104">İş akışları, <xref:System.Activities.Statements.TryCatch> bir iş akışının yürütülmesi sırasında oluşturulan özel durumları işlemek için etkinliğini kullanabilir.</span><span class="sxs-lookup"><span data-stu-id="02352-104">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="02352-105">Bu özel durumlar işlenebilir veya etkinlik kullanılarak yeniden oluşturulabilir <xref:System.Activities.Statements.Rethrow> .</span><span class="sxs-lookup"><span data-stu-id="02352-105">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="02352-106">Bölümündeki etkinlikler <xref:System.Activities.Statements.TryCatch.Finally%2A> , <xref:System.Activities.Statements.TryCatch.Try%2A> bölüm ya da <xref:System.Activities.Statements.TryCatch.Catches%2A> bölüm tamamlandığında yürütülür.</span><span class="sxs-lookup"><span data-stu-id="02352-106">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="02352-107">Bir örnek tarafından barındırılan iş akışları <xref:System.Activities.WorkflowApplication> , <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> bir etkinlik tarafından işlenmeyen özel durumları işlemek için de olay işleyicisini de kullanabilir <xref:System.Activities.Statements.TryCatch> .</span><span class="sxs-lookup"><span data-stu-id="02352-107">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="02352-108">Özel durumların nedenleri</span><span class="sxs-lookup"><span data-stu-id="02352-108">Causes of Exceptions</span></span>  

 <span data-ttu-id="02352-109">Bir iş akışında, özel durumlar aşağıdaki yollarla oluşturulabilir:</span><span class="sxs-lookup"><span data-stu-id="02352-109">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
- <span data-ttu-id="02352-110">İçindeki işlemlerin zaman aşımı <xref:System.Activities.Statements.TransactionScope> .</span><span class="sxs-lookup"><span data-stu-id="02352-110">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
- <span data-ttu-id="02352-111">Etkinlik kullanılarak iş akışı tarafından oluşturulan açık bir özel durum <xref:System.Activities.Statements.Throw> .</span><span class="sxs-lookup"><span data-stu-id="02352-111">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
- <span data-ttu-id="02352-112">[!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)]Etkinlikten özel durum oluşturuldu.</span><span class="sxs-lookup"><span data-stu-id="02352-112">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
- <span data-ttu-id="02352-113">İş akışında kullanılan kitaplıklar, bileşenler veya hizmetler gibi harici koddan oluşturulan özel durum.</span><span class="sxs-lookup"><span data-stu-id="02352-113">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="02352-114">Özel Durumları İşleme</span><span class="sxs-lookup"><span data-stu-id="02352-114">Handling Exceptions</span></span>  

 <span data-ttu-id="02352-115">Bir etkinlik tarafından bir özel durum oluşturulursa ve işlenmemiş ise, varsayılan davranış iş akışı örneğini sonlandırmak olur.</span><span class="sxs-lookup"><span data-stu-id="02352-115">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="02352-116">Özel bir <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> işleyici varsa, bu varsayılan davranışı geçersiz kılabilir.</span><span class="sxs-lookup"><span data-stu-id="02352-116">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="02352-117">Bu işleyici, iş akışı ana bilgisayarına özel günlük kaydı, iş akışını iptal etme, iş akışını iptal etme veya iş akışını sonlandırma gibi uygun işleme sağlama fırsatı verir.</span><span class="sxs-lookup"><span data-stu-id="02352-117">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="02352-118">Bir iş akışı işlenmemiş bir özel durum harekete geçirirse, <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="02352-118">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="02352-119"><xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>İş akışının nihai sonucunu belirleyen üç olası eylem döndürülür.</span><span class="sxs-lookup"><span data-stu-id="02352-119">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
- <span data-ttu-id="02352-120">**İptal** -iptal edilen bir iş akışı örneği, bir dal yürütmesinin düzgün bir şekilde çıkışı.</span><span class="sxs-lookup"><span data-stu-id="02352-120">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="02352-121">İptal davranışını modelleyebilirsiniz (örneğin, bir CancellationScope etkinliği kullanarak).</span><span class="sxs-lookup"><span data-stu-id="02352-121">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="02352-122">Tamamlanan işleyici, iptal işlemi tamamlandığında çağrılır.</span><span class="sxs-lookup"><span data-stu-id="02352-122">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="02352-123">İptal edilen bir iş akışı Iptal edildi durumunda.</span><span class="sxs-lookup"><span data-stu-id="02352-123">A cancelled workflow is in the Cancelled state.</span></span>  
  
- <span data-ttu-id="02352-124">**Sonlandır** -sonlandırılan bir iş akışı örneği sürdürülemez veya yeniden başlatılamaz.</span><span class="sxs-lookup"><span data-stu-id="02352-124">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="02352-125">Bu, sonlandırıldığı nedenden dolayı özel durum sağlayabilmeniz için tamamlanan olayı tetikler.</span><span class="sxs-lookup"><span data-stu-id="02352-125">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="02352-126">Sonlandırma işlemi tamamlandığında sonlandırılmış işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="02352-126">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="02352-127">Sonlandırılan bir iş akışı hatalı durumda.</span><span class="sxs-lookup"><span data-stu-id="02352-127">A terminated workflow is in the Faulted state.</span></span>  
  
- <span data-ttu-id="02352-128">**Abort** -durdurulan bir iş akışı örnekleri, yalnızca kalıcı olacak şekilde yapılandırıldıysa devam edebilir.</span><span class="sxs-lookup"><span data-stu-id="02352-128">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="02352-129">Kalıcı olmadan iş akışı devam ettirilemez.</span><span class="sxs-lookup"><span data-stu-id="02352-129">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="02352-130">Bir iş akışı iptal edilmediği zaman, son kalıcılık noktası bu yana gerçekleştirilen tüm işler (bellekte) kaybolacaktır.</span><span class="sxs-lookup"><span data-stu-id="02352-130">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="02352-131">Durdurulan bir iş akışı için durdurulan işleyici, durdurma işleminin tamamlanması nedeniyle özel durum kullanılarak çağrılır.</span><span class="sxs-lookup"><span data-stu-id="02352-131">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="02352-132">Ancak, Iptal edilen ve sonlandırılan aksine, tamamlanan işleyici çağrılmaz.</span><span class="sxs-lookup"><span data-stu-id="02352-132">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="02352-133">Durdurulan bir iş akışı durdurulmuş durumda.</span><span class="sxs-lookup"><span data-stu-id="02352-133">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="02352-134">Aşağıdaki örnek bir özel durum oluşturan iş akışını çağırır.</span><span class="sxs-lookup"><span data-stu-id="02352-134">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="02352-135">Özel durum iş akışı tarafından işlenmemiş ve <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> işleyici çağırılır.</span><span class="sxs-lookup"><span data-stu-id="02352-135">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="02352-136">, <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Özel durum hakkında bilgi sağlamak için denetlenir ve iş akışı sonlandırılır.</span><span class="sxs-lookup"><span data-stu-id="02352-136">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="02352-137">TryCatch etkinliğiyle özel durumları işleme</span><span class="sxs-lookup"><span data-stu-id="02352-137">Handling Exceptions with the TryCatch Activity</span></span>  

 <span data-ttu-id="02352-138">Bir iş akışı içinde özel durumların işlenmesi etkinlikle gerçekleştirilir <xref:System.Activities.Statements.TryCatch> .</span><span class="sxs-lookup"><span data-stu-id="02352-138">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="02352-139"><xref:System.Activities.Statements.TryCatch>Etkinlik, <xref:System.Activities.Statements.TryCatch.Catches%2A> <xref:System.Activities.Statements.Catch> her biri belirli bir türle ilişkili olan etkinliklerin bir koleksiyonunu içerir <xref:System.Exception> .</span><span class="sxs-lookup"><span data-stu-id="02352-139">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="02352-140">Etkinliğin bölümünde yer alan bir etkinlik tarafından oluşturulan özel durum <xref:System.Activities.Statements.TryCatch.Try%2A> <xref:System.Activities.Statements.TryCatch> koleksiyondaki bir etkinliğin özel durumuyla eşleşiyorsa <xref:System.Activities.Statements.Catch%601> <xref:System.Activities.Statements.TryCatch.Catches%2A> , özel durum işlenir.</span><span class="sxs-lookup"><span data-stu-id="02352-140">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="02352-141">Özel durum açıkça yeniden oluşturulursa veya yeni bir özel durum oluşturulursa, bu özel durum üst etkinliğe geçirilir.</span><span class="sxs-lookup"><span data-stu-id="02352-141">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="02352-142">Aşağıdaki kod örneğinde, <xref:System.Activities.Statements.TryCatch> <xref:System.ApplicationException> <xref:System.Activities.Statements.TryCatch.Try%2A> bir etkinlik tarafından bölümünde oluşan bir etkinliği işleyen bir etkinlik gösterilmektedir <xref:System.Activities.Statements.Throw> .</span><span class="sxs-lookup"><span data-stu-id="02352-142">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="02352-143">Özel durumun iletisi, etkinlik tarafından konsola yazılır <xref:System.Activities.Statements.Catch%601> ve ardından, bölümündeki konsola bir ileti yazılır <xref:System.Activities.Statements.TryCatch.Finally%2A> .</span><span class="sxs-lookup"><span data-stu-id="02352-143">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="02352-144">Bölümündeki etkinlikler, <xref:System.Activities.Statements.TryCatch.Finally%2A> <xref:System.Activities.Statements.TryCatch.Try%2A> bölüm ya da <xref:System.Activities.Statements.TryCatch.Catches%2A> bölüm başarıyla tamamlandığında yürütülür.</span><span class="sxs-lookup"><span data-stu-id="02352-144">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="02352-145"><xref:System.Activities.Statements.TryCatch.Try%2A>Bu bölüm, bundan hiçbir özel durum atılmadı ve bu bölüm, <xref:System.Activities.Statements.TryCatch.Catches%2A> herhangi bir özel durum atılmadı veya yeniden oluşturulursa bölüm başarıyla tamamlanır.</span><span class="sxs-lookup"><span data-stu-id="02352-145">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="02352-146">Bir özel durum ' <xref:System.Activities.Statements.TryCatch.Try%2A> a bölümünde oluşturulursa <xref:System.Activities.Statements.TryCatch> ve bölümünde bir ile işlenmezse <xref:System.Activities.Statements.Catch%601> veya ' <xref:System.Activities.Statements.TryCatch.Catches%2A> den yeniden oluşturulursa, ' <xref:System.Activities.Statements.TryCatch.Catches%2A> deki etkinlikler, <xref:System.Activities.Statements.TryCatch.Finally%2A> aşağıdakilerden biri gerçekleşmediği takdirde yürütülmeyecektir.</span><span class="sxs-lookup"><span data-stu-id="02352-146">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
- <span data-ttu-id="02352-147">Özel durum, <xref:System.Activities.Statements.TryCatch> Bu üst düzeyden yeniden oluşturulup oluşturulmayacağını bağımsız olarak iş akışında daha yüksek düzey bir etkinlik tarafından yakalanır <xref:System.Activities.Statements.TryCatch> .</span><span class="sxs-lookup"><span data-stu-id="02352-147">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
- <span data-ttu-id="02352-148">Özel durum daha yüksek bir düzeyde işlenmez <xref:System.Activities.Statements.TryCatch> , iş akışının kökünü çıkar ve iş akışı Sonlandır veya Durdur yerine iptal etmek üzere yapılandırılır.</span><span class="sxs-lookup"><span data-stu-id="02352-148">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="02352-149">Kullanılarak barındırılan iş akışları <xref:System.Activities.WorkflowApplication> , işleme <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> ve döndürerek bunu yapılandırabilir <xref:System.Activities.UnhandledExceptionAction.Cancel> .</span><span class="sxs-lookup"><span data-stu-id="02352-149">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="02352-150"><xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>Bu konuda daha önce bir işleme örneği verilmiştir.</span><span class="sxs-lookup"><span data-stu-id="02352-150">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="02352-151">İş akışı hizmetleri, kullanarak <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> ve belirterek bunu yapılandırabilir <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel> .</span><span class="sxs-lookup"><span data-stu-id="02352-151">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="02352-152">Yapılandırma örneği için <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> bkz. [Iş akışı hizmeti konak genişletilebilirliği](../wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="02352-152">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="02352-153">Özel durum Işleme ve Dengeleme</span><span class="sxs-lookup"><span data-stu-id="02352-153">Exception Handling versus Compensation</span></span>  

 <span data-ttu-id="02352-154">Özel durum işleme ve dengeleme arasındaki fark, bir etkinliğin yürütülmesi sırasında özel durum işlemenin meydana geldi.</span><span class="sxs-lookup"><span data-stu-id="02352-154">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="02352-155">Bir etkinlik başarıyla tamamlandıktan sonra Dengeleme oluşur.</span><span class="sxs-lookup"><span data-stu-id="02352-155">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="02352-156">Özel durum işleme, etkinlik özel durumu harekete geçirdikten sonra temizlik için bir fırsat sağlar, ancak dengeleme, daha önce tamamlanmış bir etkinliğin başarıyla tamamlanmasıyla birlikte geri alınabilecek bir mekanizma sağlar.</span><span class="sxs-lookup"><span data-stu-id="02352-156">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="02352-157">Daha fazla bilgi için bkz. [Dengeleme](compensation.md).</span><span class="sxs-lookup"><span data-stu-id="02352-157">For more information, see [Compensation](compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="02352-158">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="02352-158">See also</span></span>

- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
